EXIT_CODE_INCORRECT_CREDENTIALS = 3
EXIT_CODE_NO_MATCHES_FOUND = 200
EXIT_CODE_INVALID_FILE_PATH = 201
EXIT_CODE_SFTP_MOVE_ERROR = 202
EXIT_CODE_SFTP_DELETE_ERROR = 203
EXIT_CODE_SFTP_DOWNLOAD_ERROR = 204
